name: 🐛 | Bug Submission
description: 🎤 | Submit the bugs you've found in this mod.
title: "[BUG]: "
labels: ["BUG"]
body:
- type: markdown
  attributes:
    value: "# 🎁 | Welcome to fill in the bug feedback for this mod!"
- type: checkboxes
  id: BUG_Prefeedback
  attributes:
    label: Checklist
    description: "Before submitting, please confirm the following:"
    options:
      - label: This bug has not been submitted before.
        required: true
      - label: The fix for this bug is not in the PR.
        required: true
      - label: I have updated the mod to the latest version.
        required: true
- type: input
  id: Version
  attributes:
    label: Version
    description: The mod version, Minecraft version, and loader you were using when you found this bug.
    placeholder: "Mod version: vx.x.x; Minecraft version: x.x.x; Mod loader: ***"
  validations:
    required: true
- type: textarea
  id: BUGInMSS3_Retry
  attributes:
    label: Reproduction Steps
    description: Please briefly describe how to trigger this bug.
    placeholder: |
      1. xxx
      2. xxx
      3. xxx
  validations:
    required: true
- type: textarea
  id: UploadLog
  attributes:
    label: Remarks
    description: [Optional] Upload your launcher log and your game log (usually in `.minecraft\versions\<version folder>\logs`).
  validations:
    required: false
- type: markdown
  attributes:
    value: "### 🎉 | Thank you for your support of this mod!" 