Name: 📖 | New Feature Submission
Description: 📎 | Write down some of your suggestions for adding new features.
Title: "[New Feature]: "
Labels: ["New Feature Suggestion"]
Body:
- Type: markdown
  Attributes:
    Value: "# 🎁 | You are filling in the new feature suggestions for this mod!"
- Type: checkboxes
  Id: Prefeedback
  Attributes:
    Label: Checklist
    Description: "Before submitting, please confirm the following:"
    Options:
      - Label: This feature has not been proposed before.
        Required: true
      - Label: This feature is not in the PR.
        Required: true
      - Label: This feature has not been added in the latest version of the mod.
        Required: true
- Type: input
  Id: FeatureRequest_Summary
  Attributes:
    Label: Brief Introduction
    Description: Please briefly describe the new feature you hope to add.
    Placeholder: |
      <Brief description of this feature>
- Type: textarea
  Id: FeatureRequest_Steps
  Attributes:
    Label: Details
    Description: Please describe the content of the new feature in detail, as well as the reasons why this feature is needed.
    Placeholder: |
      <Detailed content of this feature>
- Type: markdown
  Attributes:
    Value: "### 🎉 | Thank you for your support of this mod!"