name: Check commands 1.16
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mcbeet/check-commands@v1
        with:
          source: .
          minecraft: "1.16"
